name: Zips on deploy branch

on:
  push:
    branches:
      - trunk

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: deploy
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.1
      - name: Merge trunk -> deploy
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: trunk
          target_branch: deploy
          github_token: ${{ secrets.GH_ACTION_BLOCK_EXAMPLES }}
      - name: Show current branch
        run: git branch --show-current
      - name: Show last commit
        run: git log --oneline --graph
      - name: Pull changes for branch deploy
        run: git pull origin deploy
      - name: Show last commit
        run: git log --oneline --graph
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run deploy
        run: npm run deploy
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: deploy